backend:
  name: github
  repo: suncoast-devs/web
display_url: https://suncoast.io
media_folder: static/media
public_folder: /media
collections:
  - name: faqs
    label: FAQs
    folder: data/faqs
    create: true
    fields:
      - name: title
        label: Question
      - name: body
        label: Answer
        widget: markdown
      - name: position
        label: Position (for ordering)
        widget: number
  - name: organizations
    label: Organizations
    folder: data/organizations
    create: true
    format: json
    fields:
      - name: title
        label: Organization Name
        required: true
      - name: url
        label: URL
        required: true
      - name: thumbnail
        label: Thumbnail Image / Logo
        widget: image
      - name: founded_on
        label: Foundation Date
        widget: date
  - name: people
    label: People
    folder: data/people
    create: true
    fields:
      - name: title
        label: Name
        widget: string
      - name: role
        lable: Title / Role
        widget: string
      - name: long_bio
        label: Long Biography
        widget: markdown
      - name: short_bio
        label: Short Biography
        widget: markdown
      - name: photo
        label: Photo/Headshot
        widget: image
  - name: posts
    label: Posts
    folder: data/posts
    create: true
    slug: '{{slug}}'
    fields:
      - name: title
        label: Title
        widget: string
        tagname: h1
      - name: body
        label: Body
        widget: markdown
        tagname: h1
      - name: date
        label: Publication Date
        widget: datetime
      - name: image
        label: Featured Image
        widget: image
      - name: description
        label: Description / Summary
        widget: text
      - name: draft
        label: Draft?
        widget: boolean
        default: true
      - name: author
        label: Post Author
        widget: relation
        collection: people
        searchFields: ['title']
        valueField: title
